// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Models.Entities;

[Table("contrato")]
public partial class Contrato : BaseEntity
{
    public int ArrendadorId { get; set; }

    public int ArrendatarioId { get; set; }

    public int PropiedadId { get; set; }

    public int FiadorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Emision { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Termino { get; set; }
}