// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Core.Models.Entities;

[Table("contrato")]
public partial class Contrato : BaseEntity
{
    [Required]
    public int ArrendadorId { get; set; }

    [Required]
    public int ArrendatarioId { get; set; }

    [Required]
    public int PropiedadId { get; set; }

    [Required]
    public int InteriorId { get; set; }

    public int FiadorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Termino { get; set; }

    [StringLength(4000)]
    public string CondicionesAdicionales  { get; set; } = null;


    [NotMapped]
    public List<Renovacion> Renovacion { get; set; } = new List<Renovacion>();

    [AllowNull]
    public Fiador Fiador { get; set; } = new Fiador();

    [AllowNull]
    public Arrendatario Arrendatario { get; set; } = new Arrendatario();

    [AllowNull]
    public Interior Interior { get; set; } = new Interior ();
}