// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Models.Entities;

[Table("propiedad")]
public partial class Propiedad : BaseEntity
{
    [StringLength(100)]
    public string Alias { get; set; }

    [Precision(10, 0)]
    public decimal Precio { get; set; }

    public bool Libre { get; set; }

    [Required]
    [StringLength(100)]
    public string Direccion { get; set; }

    [Required]
    [StringLength(100)]
    public string Municipio { get; set; }

    [Required]
    [StringLength(100)]
    public string Colonia { get; set; }
}