# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build
  #     run: dotnet build --no-restore
  #  # - name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Deploy
      id: deploy
      #timeout-minutes: 1
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{secrets.QA_ARRENDAMIENTO_DEPLOY_BACKEND}}/${{secrets.QA_DEPLOY_KEY}}' #'http://alfredowflsyopollo.us:5000/api/deploy/1'
        method: 'GET'
        timeout: 100000

        

      
