# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Deploy
      id: deploy
      timeout-minutes: 1
      uses: muhfaris/request-action@v0.1.2
      with:
          #url: ${{ secrets.API_URL }}
          #headers: ${{ secrets.API_HEADERS }}
          url: http://alfredowflsyopollo.us:5000/api/deploy/1
          #body: |
           # {
            #  "key": "value"
            #}
          method: POST

    - name: Show API Response Status
      run: |
        echo "Response Status: ${{ steps.deploy.outputs.response-status }}"
  
    - name: Show API Response Data
      run: |
        echo "Response Data: ${{ steps.deploy.outputs.response-data }}"


      
